name: deploy

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ vars.IMAGE_TAG }}
      - name: Update container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PK }}
          passphrase: ${{ secrets.SSH_PP }}
          script: |
            docker stop ${{ vars.CONTAINER_NAME }}
            docker rm ${{ vars.CONTAINER_NAME }}
            docker pull ${{ vars.IMAGE_TAG }}
            docker run \
              -d \
              -e NODE_ENV=production \
              -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
              -e GPT_KEY=${{ secrets.GPT_KEY }} \
              --name ${{ vars.CONTAINER_NAME }} \
              -v ~/data/chatstats/:/app/data/ \
              --restart always \
              ${{ vars.IMAGE_TAG }}
